require('core-js/stable')
require('regenerator-runtime/runtime')

const logo = require('./medias/images/logo.png')
const imagem_secundaria = require('./medias/images/imagem_secundaria.png')
const storageImage = require('./medias/images/storage.jpg')
const trucks = require('./medias/images/trucks.jpg')
const noise = require('./medias/images/noise.jpg')
const noise2 = require('./medias/images/noise-2.jpg')
const graySlideImage = require('./medias/images/gray-slide-image.jpg')
const graySlideImagePortrait = require('./medias/images/gray-slide-image-portrait.jpg')
const brownSlideImage = require('./medias/images/brown-slide-image.jpg')
const brownSlideImagePortrait = require('./medias/images/brown-slide-image-portrait.jpg')
const blueSlideImage = require('./medias/images/blue-slide-image.jpg')
const blueSlideImagePortrait = require('./medias/images/blue-slide-image-portrait.jpg')
const contactUs = require('./medias/images/contact-us.jpg')
const favicon16 = require('./medias/images/favicon-16x16.png')
const favicon32 = require('./medias/images/favicon-32x32.png')
const processoFiscal = require('./medias/images/processo-fiscal-1.jpg')
const recebimento = require('./medias/images/recebimento.jpg')
const manuseio = require('./medias/images/manuseio.jpg')
const storage1 = require('./medias/images/storage-1.jpg')
const wms = require('./medias/images/wms.jpg')
const truck2 = require('./medias/images/truck-2.jpg')

const favIcon = require('./medias/svgs/symbol-defs.svg')

const faq = require('./js/faq')
const menu = require('./js/menu')
const onload = require('./js/onload')
const toggleMenu = require('./js/toggleMenu')

// require('./sass/base/_fonts.scss')

const aeonikBoldFont = require('./medias/fonts/aeonik/Aeonik-Bold.otf')
const aeonikRegularFont = require('./medias/fonts/aeonik/Aeonik-Regular.otf')
const aeonikLightFont = require('./medias/fonts/aeonik/Aeonik-Light.otf')
const aeonikThinFont = require('./medias/fonts/aeonik/Aeonik-Thin.otf')
// const aeonikAirItalicFont = require('./medias/fonts/aeonik/Aeonik-AirItalic.otf')