require('core-js/stable')
require('regenerator-runtime/runtime')

const logo = require('./medias/images/logo.png')
const imagem_secundaria = require('./medias/images/imagem_secundaria.png')
const storageImage = require('./medias/images/storage.jpg')
const trucks = require('./medias/images/trucks.jpg')
const noise = require('./medias/images/noise.jpg')
const noise2 = require('./medias/images/noise-2.jpg')
const graySlideImage = require('./medias/images/gray-slide-image.jpg')
const brownSlideImage = require('./medias/images/brown-slide-image.jpg')
const blueSlideImage = require('./medias/images/blue-slide-image.jpg')
const userImage = require('./medias/images/foto_usuario.png')
const contactUs = require('./medias/images/contact-us.jpg')
const favicon16 = require('./medias/images/favicon-16x16.png')
const favicon32 = require('./medias/images/favicon-32x32.png')

const favIcon = require('./medias/svgs/symbol-defs.svg')

const faq = require('./js/faq')
const menu = require('./js/menu')
const onload = require('./js/onload')

const aeonikRegularFont = require('./medias/fonts/aeonik/Aeonik-Regular.otf')
const aeonikLightFont = require('./medias/fonts/aeonik/Aeonik-Light.otf')
const aeonikAirFont = require('./medias/fonts/aeonik/Aeonik-Air.otf')
const aeonikAirItalicFont = require('./medias/fonts/aeonik/Aeonik-AirItalic.otf')